- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
    - name: Get EdgeOS Version
      commands:
        - show version
      wait_for:
        - "result[0] contains 'EdgeOS'"
