- name: Test Reachability of Routers
  hosts: all
  tasks:
      debug:
        msg: "Test reachability to sandbox-pknpddwdrc.dynamic-m.com"
      net_ping:
        dest: sandbox-pknpddwdrc.dynamic-m.com
